import { useState } from 'react'
import './App.css'
import { DEFAULT_TEST_DATE, daysUntil, formatTargetDate, groceryItems } from './domain/plan'

type Tab = 'today' | 'chat' | 'groceries' | 'progress'
type Language = 'en' | 'ur'
type Profile = { name: string; age: string }
type ChatMessage = { role: 'user' | 'assistant'; text: string }

const quickActions = { en: ['Done', 'Doing now', 'Not available', 'Give alternative'], ur: ['ہو گیا', 'اب کر رہا ہوں', 'دستیاب نہیں', 'متبادل دیں'] }
const copy = {
  en: { today: 'Today', chat: 'Chat', groceries: 'Groceries', progress: 'Progress', settings: 'Settings', coach: 'Private coach', greeting: 'Your day,', subtitle: 'Small steps. Consistent progress.', streak: 'day streak', test: 'Until follow-up test', target: 'Target: November 2, 2026', next: 'What to do now', task: 'Eggs, roti, fruit and yoghurt', taskDetail: '2 boiled eggs + 1 roti + 1 fruit + yoghurt', reason: 'For protein and daily nutrition balance', review: "Today's review", details: 'View details', meals: 'meals', sleep: 'hours sleep', water: 'water', tip: 'Coach tip', tipText: 'Walk for 30 minutes today. Ten minutes after a meal also counts.', welcome: 'Welcome to MetaBotism', intro: 'Your private adherence coach. Let’s personalise your plan.', name: 'Your name', age: 'Your age', namePlaceholder: 'Enter your name', agePlaceholder: 'Enter your age', continue: 'Continue', chatTitle: 'Your coach', available: 'Available now', chatGreeting: 'Hello! I’m ready to help you stay on track today.', chatPrompt: 'What would you like to do next?', listTitle: "This week's list", copyList: 'Copy grocery list', score: "This week's score", better: '12% better than last week' },
  ur: { today: 'آج', chat: 'چیٹ', groceries: 'گروسریز', progress: 'پروگریس', settings: 'ترتیبات', coach: 'ذاتی کوچ', greeting: 'آپ کا دن،', subtitle: 'چھوٹے قدم، مسلسل بہتری۔', streak: 'دن مسلسل', test: 'فالو اَپ ٹیسٹ تک', target: 'ہدف: ۲ نومبر ۲۰۲۶', next: 'اب کیا کرنا ہے', task: 'انڈے، روٹی، پھل اور دہی', taskDetail: '۲ اُبلے انڈے + ۱ روٹی + ۱ پھل + دہی', reason: 'پروٹین اور روزانہ غذائی توازن کے لیے', review: 'آج کا جائزہ', details: 'تفصیل دیکھیں', meals: 'کھانے', sleep: 'گھنٹے نیند', water: 'پانی', tip: 'کوچ کا مشورہ', tipText: 'آج ۳۰ منٹ چہل قدمی کریں۔ کھانے کے بعد ۱۰ منٹ بھی فائدہ مند ہیں۔', welcome: 'MetaBotism میں خوش آمدید', intro: 'آپ کا ذاتی adherence coach۔ آئیے پلان کو ذاتی بناتے ہیں۔', name: 'آپ کا نام', age: 'آپ کی عمر', namePlaceholder: 'نام لکھیں', agePlaceholder: 'عمر لکھیں', continue: 'جاری رکھیں', chatTitle: 'آپ کا کوچ', available: 'ابھی دستیاب ہے', chatGreeting: 'السلام علیکم! میں آج آپ کو ٹریک پر رہنے میں مدد دوں گا۔', chatPrompt: 'اگلا کام کیا کرنا ہے؟', listTitle: 'اس ہفتے کی فہرست', copyList: 'گروسری لسٹ کاپی کریں', score: 'اس ہفتے کا اسکور', better: 'گزشتہ ہفتے سے ۱۲٪ بہتر' },
}

function App() {
  const [profile, setProfile] = useState<Profile | null>(() => { const saved = localStorage.getItem('metabotism-profile'); return saved ? JSON.parse(saved) : null })
  const [language, setLanguage] = useState<Language>('en')
  const [nastaliq, setNastaliq] = useState(false)
  const [tab, setTab] = useState<Tab>('today')
  const [name, setName] = useState('')
  const [age, setAge] = useState('')
  const [message, setMessage] = useState('')
  const [messages, setMessages] = useState<ChatMessage[]>([])
  const [isThinking, setIsThinking] = useState(false)
  const [done, setDone] = useState(() => localStorage.getItem('metabotism-breakfast-done') === 'true')
  const [groceries, setGroceries] = useState<boolean[]>(() => { const saved = localStorage.getItem('metabotism-groceries'); return saved ? JSON.parse(saved) : groceryItems.map((_, index) => index < 2) })
  const testDate = localStorage.getItem('metabotism-test-date') || DEFAULT_TEST_DATE
  const t = copy[language]
  const rtl = language === 'ur'

  const finishOnboarding = () => { if (!name.trim() || !age.trim()) return; const next = { name: name.trim(), age: age.trim() }; localStorage.setItem('metabotism-profile', JSON.stringify(next)); localStorage.setItem('metabotism-test-date', DEFAULT_TEST_DATE); setProfile(next) }
  const toggleDone = () => { const next = !done; setDone(next); localStorage.setItem('metabotism-breakfast-done', String(next)) }
  const toggleGrocery = (index: number) => { const next = groceries.map((item, itemIndex) => itemIndex === index ? !item : item); setGroceries(next); localStorage.setItem('metabotism-groceries', JSON.stringify(next)) }
  const sendMessage = async (text = message) => { if (!text.trim() || isThinking) return; const userMessage = text.trim(); setMessages((items) => [...items, { role: 'user', text: userMessage }]); setMessage(''); setTab('chat'); setIsThinking(true); try { const response = await fetch('/api/chat', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ message: userMessage, language, profile, history: messages.slice(-12) }) }); const data = await response.json(); setMessages((items) => [...items, { role: 'assistant', text: data.reply || data.message || 'The coach is unavailable right now.' }]) } catch { setMessages((items) => [...items, { role: 'assistant', text: language === 'en' ? 'The coach is offline. Your local plan is still available.' : 'کوچ آف لائن ہے۔ آپ کا مقامی پلان پھر بھی دستیاب ہے۔' }]) } finally { setIsThinking(false) } }

  if (!profile) return <main className="onboarding" dir={rtl ? 'rtl' : 'ltr'}><div className="onboarding-brand"><div className="brand-mark">م</div><span>MetaBotism</span></div><div className="welcome-icon">✦</div><p className="eyebrow">PRIVATE ADHERENCE COACH</p><h1>{t.welcome}</h1><p className="intro-copy">{t.intro}</p><div className="form-card"><label>{t.name}<input value={name} onChange={(event) => setName(event.target.value)} placeholder={t.namePlaceholder} autoFocus /></label><label>{t.age}<input value={age} onChange={(event) => setAge(event.target.value)} placeholder={t.agePlaceholder} type="number" /></label><button className="primary-button" disabled={!name.trim() || !age.trim()} onClick={finishOnboarding}>{t.continue} <span>→</span></button></div><button className="language-switch onboarding-switch" onClick={() => setLanguage(language === 'en' ? 'ur' : 'en')}>{language === 'en' ? 'اردو' : 'English'}</button></main>

  return <main className={`shell ${nastaliq ? 'nastaliq-mode' : ''}`} dir={rtl ? 'rtl' : 'ltr'}>
    <header className="topbar"><div className="brand-lockup"><div className="brand-mark">م</div><div><div className="brand-name">MetaBotism</div><div className="brand-status"><span /> {t.coach}</div></div></div><div className="header-actions"><button className="language-switch" onClick={() => setLanguage(language === 'en' ? 'ur' : 'en')}>{language === 'en' ? 'اردو' : 'English'}</button><button className="font-switch" onClick={() => setNastaliq(!nastaliq)} aria-label="Toggle Urdu reading font">{nastaliq ? 'Aa' : 'خط'}</button><button className="icon-button" aria-label={t.settings}>⚙</button></div></header>
    {tab === 'today' && <section className="page-content"><div className="greeting-row"><div><p className="eyebrow">WEDNESDAY, JULY 22, 2026</p><h1>{t.greeting} {profile.name}</h1><p className="muted">{t.subtitle} · {profile.age}</p></div><div className="streak"><strong>7</strong><span>{t.streak}</span></div></div><div className="countdown-card"><div><span className="card-label">{t.test}</span><strong className="countdown-number">{daysUntil(testDate)} <small>{language === 'en' ? 'days' : 'دن'}</small></strong><span className="countdown-note">{t.target} · {formatTargetDate(testDate, language)}</span></div><div className="ring"><span>41%</span></div></div><div className="section-heading"><h2>{t.next}</h2><span>{done ? '2 / 4' : '1 / 4'}</span></div><article className={`task-card ${done ? 'completed' : ''}`}><div className="task-icon">🥣</div><div className="task-copy"><span className="task-time">BREAKFAST · 8:00 - 9:00</span><h3>{t.task}</h3><p>{t.taskDetail}</p><span className="reason">{t.reason}</span></div><button className="done-button" onClick={toggleDone}>{done ? '✓' : '○'}</button></article><div className="section-heading"><h2>{t.review}</h2><button className="link-button">{t.details}</button></div><div className="stats-grid"><div className="stat-card"><span className="stat-icon green">✓</span><strong>{done ? '3 / 4' : '2 / 4'}</strong><span>{t.meals}</span></div><div className="stat-card"><span className="stat-icon blue">♨</span><strong>7:45</strong><span>{t.sleep}</span></div><div className="stat-card"><span className="stat-icon orange">◒</span><strong>0.5 L</strong><span>{t.water}</span></div></div><div className="coach-tip"><span>✦</span><div><strong>{t.tip}</strong><p>{t.tipText}</p></div></div></section>}
    {tab === 'chat' && <section className="chat-page"><div className="chat-header"><div className="avatar">م</div><div><h2>{t.chatTitle}</h2><span>{isThinking ? (language === 'en' ? 'Thinking...' : 'سوچ رہا ہے...') : t.available}</span></div></div><div className="messages"><div className="date-pill">{language === 'en' ? 'Today' : 'آج'}</div><div className="bubble coach"><p>{t.chatGreeting}</p><p>{t.chatPrompt}</p><span>8:16 ✓✓</span></div>{messages.map((item, index) => <div className={`bubble ${item.role === 'assistant' ? 'coach' : 'user'}`} key={`${item.text}-${index}`}><p>{item.text}</p><span>now ✓✓</span></div>)}{isThinking && <div className="bubble coach typing"><p>•••</p></div>}</div><div className="chat-composer"><button aria-label="Voice">🎙</button><input value={message} onChange={(event) => setMessage(event.target.value)} onKeyDown={(event) => event.key === 'Enter' && void sendMessage()} placeholder={language === 'en' ? 'Type a message...' : 'پیغام لکھیں...'} /><button aria-label="Send" onClick={() => void sendMessage()}>➤</button></div><div className="quick-actions">{quickActions[language].map((action) => <button key={action} onClick={() => void sendMessage(action)}>{action}</button>)}</div></section>}
    {tab === 'groceries' && <section className="page-content"><p className="eyebrow">{t.listTitle}</p><h1>{t.groceries}</h1><div className="list-card">{groceryItems.map((item, index) => <button className="list-row grocery-button" key={item} onClick={() => toggleGrocery(index)}><span className={groceries[index] ? 'check checked' : 'check'}>✓</span><span>{item}</span><small>{groceries[index] ? 'Available' : 'To buy'}</small></button>)}</div><button className="primary-button">{t.copyList}</button></section>}
    {tab === 'progress' && <section className="page-content"><p className="eyebrow">{t.score}</p><h1>{t.progress}</h1><div className="score-card"><span>{t.score}</span><strong>78%</strong><div className="progress-bar"><i style={{ width: '78%' }} /></div><p>{t.better}</p></div><div className="list-card progress-list"><div><span>Meals</span><strong>86%</strong></div><div><span>Walking</span><strong>71%</strong></div><div><span>Sleep</span><strong>80%</strong></div><div><span>Water</span><strong>64%</strong></div></div></section>}
    <nav className="bottom-nav">{([['today', '⌂', t.today], ['chat', '◌', t.chat], ['groceries', '▤', t.groceries], ['progress', '◔', t.progress]] as [Tab, string, string][]).map(([key, icon, label]) => <button className={tab === key ? 'active' : ''} key={key} onClick={() => setTab(key)}><span>{icon}</span>{label}</button>)}</nav>
  </main>
}

export default App
