import { useState } from 'react'
import './flow-screens.css'

type Lang = 'en' | 'ur'
const copy = { en: { library:'Reports library', upload:'Upload new report', processing:'Report processing', analysis:'Report analysis', compare:'Progress comparison', back:'Back to reports', intro:'Keep raw reports together and compare like with like.', choose:'Choose a report file', process:'Start processing', saved:'Saved reports', file:'July 2026 semen analysis', metrics:'Key metrics', disclaimer:'This is context for your approved plan, not a diagnosis.' }, ur: { library:'رپورٹس لائبریری', upload:'نئی رپورٹ اپ لوڈ کریں', processing:'رپورٹ پروسیسنگ', analysis:'رپورٹ کا تجزیہ', compare:'پیش رفت کا موازنہ', back:'رپورٹس پر واپس', intro:'خام رپورٹس محفوظ رکھیں اور ایک جیسے ڈیٹا کا موازنہ کریں۔', choose:'رپورٹ فائل منتخب کریں', process:'پروسیسنگ شروع کریں', saved:'محفوظ رپورٹس', file:'جولائی 2026 سیمن تجزیہ', metrics:'اہم پیمانے', disclaimer:'یہ منظور شدہ پلان کا سیاق ہے، تشخیص نہیں۔' } }
export default function ReportsFlow({ language }: { language: Lang }) { const t=copy[language]; const [screen,setScreen]=useState<'library'|'upload'|'processing'|'analysis'|'compare'>('library'); const [file,setFile]=useState(()=>localStorage.getItem('metabotism:last-report')||''); const go=(s:typeof screen)=>setScreen(s); if(screen==='library') return <FlowShell title={t.library} intro={t.intro}><div className="flow-grid"><FlowCard title={t.upload} text={t.choose} onClick={()=>go('upload')} /><FlowCard title={t.analysis} text={t.metrics} onClick={()=>go('analysis')} /><FlowCard title={t.compare} text="April 2025 → July 2026" onClick={()=>go('compare')} /></div><div className="flow-panel"><b>{t.saved}</b><p>{file || t.file} · local device</p><button className="outline-button" onClick={()=>go('analysis')}>{t.analysis} →</button></div></FlowShell>; if(screen==='upload') return <FlowShell title={t.upload} intro={t.choose}><div className="upload-zone"><input type="file" accept=".pdf,.jpg,.jpeg,.png" onChange={e=>{const next=e.target.files?.[0]?.name || ''; setFile(next); if(next) localStorage.setItem('metabotism:last-report',next)}}/><strong>{file || 'PDF, JPG or PNG'}</strong><small>Raw report stays local until a backend is connected.</small></div><button className="dark-button" disabled={!file} onClick={()=>go('processing')}>{t.process} →</button><Back text={t.back} onClick={()=>go('library')}/></FlowShell>; if(screen==='processing') return <FlowShell title={t.processing} intro="Preparing a safe, readable summary."><div className="processing"><span className="loader"/><b>{file || t.file}</b><p>Reading values · checking units · preparing comparison</p></div><button className="dark-button" onClick={()=>go('analysis')}>{t.analysis} →</button></FlowShell>; return <FlowShell title={screen==='analysis'?t.analysis:t.compare} intro={screen==='analysis'?t.metrics:'April 2025 and July 2026 · raw samples only'}><div className="metric-table">{[['Concentration','32','23','−9'],['Total motility','37.5','39.13','+1.63'],['Progressive','23','23','No change'],['Rapid linear','0','0','No change'],['Normal morphology','1','1','No change']].map(r=><div className="metric-row" key={r[0]}><b>{r[0]}</b><span>Apr 2025 <strong>{r[1]}</strong></span><span>Jul 2026 <strong>{r[2]}</strong></span><em>{r[3]}</em></div>)}</div><div className="safe-note">ⓘ {t.disclaimer}</div><Back text={t.back} onClick={()=>go('library')}/></FlowShell> }
function FlowShell({title,intro,children}:{title:string;intro:string;children:React.ReactNode}) { return <div className="flow-screen"><span className="eyebrow">REPORTS</span><h1>{title}</h1><p className="flow-intro">{intro}</p>{children}</div> }
function FlowCard({title,text,onClick}:{title:string;text:string;onClick:()=>void}) { return <button className="flow-card" onClick={onClick}><span>↗</span><b>{title}</b><small>{text}</small></button> }
function Back({text,onClick}:{text:string;onClick:()=>void}) { return <button className="back-link" onClick={onClick}>← {text}</button> }
